---
arch_profile: laptop

# Laptop profile defaults
display_manager_packages:
  - sddm

laptop_power_packages:
  - tlp
  - tlp-rdw
  - acpi
  - acpid

enable_sddm: true
enable_tlp: true
install_flatpak_emulators: true
