[arch_desktops]
desktop ansible_host=10.0.0.204 ansible_user=r4wm

[arch_laptops]
# laptop ansible_host=10.0.0.205 ansible_user=r4wm

[arch_desktops:vars]
ansible_python_interpreter=/usr/bin/python3

[arch_laptops:vars]
ansible_python_interpreter=/usr/bin/python3
